### ISSUE TITLE
About link on the Navigation bar 

### ISSUE THREAD

**Issue by Eugieno** [Marilena-C/Travel-Planner_Project1#5]
### User story:
As a visitor to the site, I want to be able to view an about me section that tells me more about the App
### Acceptance criteria: 
1. When the about link is clicked, the  "About" contents pops up to the center of the web-page
2. Use querry modal mesage widget;
    Follow link for guide: https://jqueryui.com/dialog/#modal-message   

### NB 2: Remember to do a git pull to get the current version of our app, and create a feature branch as well.

**Comment by Glutey** [comment]
Task fulfilled, Additions pushed to Git repo via newly created branch entitled 'About-Modal'.
