### ISSUE TITLE
Create footer 

### ISSUE THREAD

**Issue by Eugieno** [Marilena-C/Travel-Planner_Project1#7]
### User story
As a user, I want to quickly and easily find important info on this web app 

### Acceptance criteria
1. A footer bar that has all the nav items in the main nav bar
2. A footer bar that has social icon linked to "contact us" item in the nav bar
3. A copyright statement flushed to the bottom centre of the page.

**Comment by Marilena-C** [comment]
Footer added in html and css files attached.

**Comment by Eugieno** [comment]
Completed!
